#ifndef PTX_GENERATOR_HPP
#define PTX_GENERATOR_HPP

#include "ast.hpp"
#include <sstream> //string stream
#include <string>
#include <unordered_map>
#include <vector>

// global scope variable manager, simplified 
class GlobalScope {
    std::unordered_map<std::string, int> var_to_reg; 
    int next_reg = 0; 
public: 
    int get_register(const std::string& var) {
        if (var_to_reg.find(var) == var_to_reg.end()) {
            var_to_reg[var] = ++next_reg; 
        }
        return var_to_reg[var]; 
    }

    void clear() {
        var_to_reg.clear(); 
        next_reg = 0; 
    }
};

class PTXGenerator {
    std::stringstream _output; 
    GlobalScope _scope;
    std::string _file_name;
    std::vector<std::string> _param_list; 

    std::string generate_name_mangling(std::string name) {
        std::string result = "_Z"; 
        result += std::to_string(name.size()) + _file_name; 
    }
    // all INTEGER types will be .s32
public: 

    PTXGenerator(std::string name) : _file_name{name} {};

    void generate_prologue() {
        _output << "//\n//Generated by Rick's PTX Compiler\n//Based on reverse-engineering NVCC\n//\n";
        _output << ".version 9.0\n";
        _output << ".target sm_75\n"; 
        _output << ".address_size 64\n"; 

        std::string mangled = generate_name_mangling(_file_name); 

        _output << ".visible .entry " << mangled << "(\n";
        for (size_t i = 0; i < _param_list.size(); ++i) {
            _output << "    .param .u64 " << mangled << "_param_" << std::to_string(i) << "\n";
        }
        _output << ")\n{";

        // figure out a way I'm going to have global variables/parameters
        // need to be able to 
    }   
}; 

// TODO: liveness analysis here

#endif